---

fake_backend_source_repo: "git@github.com:juliencoste/fake-backend.git"
fake_backend_source_branch: "master"
fake_backend_image_tag: "CICD"

home: "/home/centos"
volume_database: "/db-data"
ip_addr_preprod: "54.160.112.136"
ip_addr_prod: "52.86.186.195"
port_app: "80"

#secret data vaulted
github_private_key: "{{ vault_github_private_key }}"
docker_hub_login: "{{ vault_docker_hub_login }}"
docker_hub_email: "{{ vault_docker_hub_email }}"
docker_hub_password: "{{ vault_docker_hub_password }}"
